version: '3.8'

volumes:
  datafiles:

# docker run --name spoton -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=spoton -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin -p 33060:3306 -d mysql/mysql-server:5.7

services:

  website:
    container_name: website
    build: app_auth/
    ports: 
        - "5000:80"
    volumes:
        - ./app_auth/:/var/www/html/
    links:
        - mysql
    restart: always

  flask:
    build: app_auth/flask/
    container_name: flask
    restart: always
    ports:
      - "5001:5001"

  mysql:
    container_name: spoton
    image: mysql:8.0.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=spoton
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - datafiles:/var/lib/mysql
      - ./app_auth/api/db/spoton.sql:/docker-entrypoint-initdb.d/spoton.sql
    restart: always
    cap_add:
      - SYS_NICE
